services:
  - type: web
    name: banque-api
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

